services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: card-games-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: card-games-frontend
    ports:
      - "3000:3000"
